# Generated by Django 4.1.7 on 2023-03-02 14:06

import api.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_mobile",
            field=models.CharField(
                default="",
                max_length=255,
                unique=True,
                validators=[api.validators.validate_email_mobile],
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_suspended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="private_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tagline",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_image",
            field=models.ImageField(
                default="avatar/default_user_image1.jpg", upload_to="images"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_login",
            field=models.DateTimeField(auto_now=True, verbose_name="last login"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="password",
            field=models.CharField(default="", editable=False, max_length=256),
        ),
    ]
