# Generated by Django 4.1.7 on 2023-03-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_newuserotp_alter_userprofile_user_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
    ]
