# Generated by Django 4.1.7 on 2023-03-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0009_another")]

    operations = [
        migrations.CreateModel(
            name="ModelBrc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pas", models.CharField(max_length=12)),
            ],
        ),
    ]
